### ISSUE TITLE
Template commands nested in {literal} ... {/literal} are still parsed.

### ISSUE THREAD

**Issue by Robert-Frampton** [Medium/soynode#63]
According to [Closure documentation](https://developers.google.com/closure/templates/docs/commands#literal) all text within `{literal}` blocks should not be parsed, including template commands.

```
{namespace test}

/**
 *
 */
{template .render}
	<div>
		{literal}
			{template .snippet}
				<span>Code snippet.</span>
			{/template}
		{/literal}
	</div>
{/template}
```

When attempting to render this template, the following error is thrown.

```
soynode: Compile error
 In file test.soy, template test.render: Lexical error at line 12, column 25.  Encountered: <EOF> after : ""
In file test.soy:12:17: parse error at '{': expected eof, {deltemplate, or {template
		{/literal}
                ^

soynode: Error: Error compiling templates
    at ChildProcess.onExit (/Projects/temp/node_modules/soynode/lib/SoyCompiler.js:308:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
soynode: emit error Error: Error compiling templates
    at ChildProcess.onExit (/Projects/temp/node_modules/soynode/lib/SoyCompiler.js:308:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

A similar error is thrown if `{namespace name}` is included inside the `{literal}` tags.

**Comment by nicks** [comment]
This package is just a nodejs wrapper around https://github.com/google/closure-templates, we do not control the template syntax.
